#!/usr/bin/env bash

SCRIPT_DIR=`dirname $(realpath "$0")`
cd $SCRIPT_DIR/..

filepath="$@"
dirpath="${filepath%.*}"

if [ -d $dirpath ]; then
    echo "$dirpath exists"
else
    mkdir -p $dirpath
    echo "$dirpath created"
fi
echo ""

cmd="markdown-code-runner $filepath"

echo "running $cmd on changes to $filepath..."
echo ""
entr $cmd <<< $filepath
echo ""
echo "...stopping watching"
